Parameters:
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: 
        - !Select 
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
      DesiredCapacity: "1"
      LaunchConfigurationName: !Ref LC
      MaxSize: "1"
      MinSize: "1"
  LC:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      ImageId: !Ref ImageId
      InstanceType: t2.micro